version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db:
    driver: local
  bundle:
    driver: local
